name: "Build Commit"
on:
  push:
    branches:
      - main
env:
  OUTPUT_DIR: "app/build/outputs/apk/release"
  SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
  SIGN_KEY_STORE_PASSWORD: ${{ secrets.SIGN_KEY_STORE_PASSWORD }}
  SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
  SIGN_KEY_STORE_FILE: "/tmp/key.jks"
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 设置JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: 设置Android SDK
        uses: android-actions/setup-android@v2
      - name: 解密签名
        run: |
          echo ${{ secrets.SIGN_KEY_BASE64 }} | base64 --decode > /tmp/key.jks
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: 构建 APK
        run: chmod a+x ./gradlew && ./gradlew assembleRelease
      - name: 安装工具
        run: |
          sudo apt-get install jq
      - name: 解析编译文件路径
        id: apk
        run: |
          versionName=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].versionName')
          versionCode=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].versionCode')
          apkFile=$(cat "${{ env.OUTPUT_DIR }}/output-metadata.json" | jq -r '.elements[0].outputFile')
          cp "${{ env.OUTPUT_DIR }}/$apkFile" "${{ env.OUTPUT_DIR }}/SkipperL-$versionName-$versionCode.apk"
          echo ::set-output name=versionName::$versionName
          echo ::set-output name=versionCode::$versionCode
      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.apk.outputs.versionName }}
          body: ${{ steps.apk.outputs.versionName }}
          files: |
            ${{ env.OUTPUT_DIR }}/SkipperL-${{ steps.apk.outputs.versionName }}-${{ steps.apk.outputs.versionCode }}.apk